### ISSUE TITLE
Issue running pod install

### ISSUE THREAD

**Issue by palcalde** [antiguab/BAFluidView#10]
Hey just want to let you know that doing just pod install on the Example folder triggered this error:

[!] Unable to satisfy the following requirements:
- `BAFluidView (from`../`)` required by `Podfile`
- `BAFluidView (from`../`)` required by `Podfile`
- `BAFluidView (= 0.1.1)` required by `Podfile.lock`

However, running pod update after solved it.

**Comment by antiguab** [comment]
Ah that's because I didn't commit after running "pod update". The PodFile.lock is out of date. I'll fix it, but you can also do it too. Before running "pod install" in the Example directory, run "pod update". Let me know if that solves your issue!

**Comment by palcalde** [comment]
Yep, as I mentioned doing pod update fixed it :+1:

**Comment by antiguab** [comment]
Ha! How did I miss your last sentence? Either way it's updated and thanks for catching that goof :)

**Comment by palcalde** [comment]
Np, btw, awesome library. I loved going thro the logic of how you implemented it. Its awesome :)

**Comment by antiguab** [comment]
Thanks! It's great to hear that the logic makes sense to people other than myself :)

**Comment by palcalde** [comment]
Absolutely. I even learnt a lot by just seeing how you made everything with just 3 animations, one horizontal one vertical and one that changes the waves. It's just fantastic :+1:
