### ISSUE TITLE
Create reverse fill out animation

### ISSUE THREAD

**Issue by gdimoff** [antiguab/BAFluidView#12]
Is it possible to achieve a fill out only animation or just a reverse fill starting from full fill to empty fill ?

**Comment by antiguab** [comment]
Yeah you can do something like this:

``` objc
    fluidView = [[BAFluidView alloc] initWithFrame:self.view.frame startElevation:@1.0];
    fluidView.fillColor = [UIColor colorWithHex:0x397ebe];
    fluidView.fillAutoReverse = NO;
    fluidView.fillRepeatCount = 1;
    [fluidView fillTo:@0.3];
    [fluidView startAnimation];
```

you'll end up with this:
![issue12](https://cloud.githubusercontent.com/assets/1091262/8639323/409d11bc-288b-11e5-84c0-b61c1e0f20df.gif)
