### ISSUE TITLE
Animation glitched after entering background

### ISSUE THREAD

**Issue by andreamazz** [antiguab/BAFluidView#14]
Hi! 
Looks like the wave animation bugs out when the app goes in the background. You can reproduce the issue in the demo app in the simulator by getting back home and reopening the app. The vertical animation runs fine, but the crests are now fixed (the amplitude changes a bit, but they keep the same overall shape).

**Comment by antiguab** [comment]
Fixed by adding your pull request and adding `viewWillMoveToWindow:` to `BAFluidView`. Thanks again! :+1:

**Comment by andreamazz** [comment]
:+1:
