### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Eke** [antiguab/BAFluidView#25]
After applications goes to background and returns to foreground BAFluidView causes memory issue and app crashes with error : `Terminated due to memory issue` . I thinks something strange is happening in `getBezierPathValues` method but ca't figure it out.

Can you please give some idea how to fix this?

**Comment by antiguab** [comment]
Have you tried using Activity Monitor via instruments to see if its `BAFluidView` that's consuming all the memory? Looking at Memory usage and activity monitor, I'm not seeing it consume much memory (I'm using the demo as a test). 

Memory Usage:
![screen shot 2015-11-09 at 7 51 02 pm](https://cloud.githubusercontent.com/assets/1091262/11053999/46f8e4f2-871b-11e5-9160-285b73df963a.png)

Activity Monitor (All Heap):
![screen shot 2015-11-09 at 7 43 34 pm](https://cloud.githubusercontent.com/assets/1091262/11053978/001bbabe-871b-11e5-8e46-7bec6e6159d8.png)

**Comment by antiguab** [comment]
Closed due to Inactivity

**Comment by antiguab** [comment]
Try updating to version 0.1.7 - it has a fix for a memory fix bug that was found
