### ISSUE TITLE
RGB color with fillColor

### ISSUE THREAD

**Issue by charlestruluck** [antiguab/BAFluidView#37]
There's an issue with using UIColor red green blue where there's no background, just the top outline.

**Comment by antiguab** [comment]
hey @charlestruluck - any chance you can post an image of the issue?

**Comment by antiguab** [comment]
closed due to inactivity

**Comment by charlestruluck** [comment]
Actually, it's started working. I guess it was an issue with Swift or Xcode?

**Comment by antiguab** [comment]
Could be! These Swift vs Objc bugs have been creeping up more and more. Glad it's working, though! 👍
