### ISSUE TITLE
Tilt Rotation not working

### ISSUE THREAD

**Issue by gsapienza** [antiguab/BAFluidView#43]
I send the notification and the breakpoints hit the correct lines in the tilt animation, but it just won't perform the animation. Any ideas?

**Comment by antiguab** [comment]
Weird! Can you send me a gist or post some sample code?

**Comment by gsapienza** [comment]
Just fixed it I put the notification setup code ahead of the startTiltAnimation function, not 100% sure why it worked, but I may have missed something. Maybe you have some insight

```
if _motionManager.deviceMotionAvailable {
        _motionManager.deviceMotionUpdateInterval = 0.3
        _motionManager.startDeviceMotionUpdatesToQueue(NSOperationQueue.mainQueue(), withHandler: { (data :CMDeviceMotion?, error :NSError?) in
            let userInfo = NSDictionary(object: data!, forKey: "data")

        NSNotificationCenter.defaultCenter().postNotificationName(kBAFluidViewCMMotionUpdate, object: nil, userInfo: userInfo as [NSObject : AnyObject])
            })
}

self._fluidView.startAnimation()
self._fluidView.startTiltAnimation()
```

**Comment by antiguab** [comment]
Glad you found a fix! 👍 - I switched the order of the animation and the device manager in the 4th case of the [demo](https://github.com/antiguab/BAFluidView/blob/master/Example/BAFluidView/BAViewController.m) and it was still receiving the notification. Here's the gist:

https://gist.github.com/antiguab/a04ee8e51359b9a2dfe2449e202e334f

Maybe it can help you out :) if you decide to change up the order again
