### ISSUE TITLE
Lagging on other animation started

### ISSUE THREAD

**Issue by chosa91** [antiguab/BAFluidView#45]
I added BAFluidView to my screen and I use SWRevealViewController to menu navigation.
IF I started to swipe in the menu, the View animation starts to lagging until I release the pull.

**Comment by antiguab** [comment]
Can you provide a code sample and a gif of the problem you are seeing? I modified the `SWRevealViewController` example project and I'm not getting any lag during gestures. 
Below is a video of my attempt:
http://d.pr/v/1ay5L

**Comment by antiguab** [comment]
Closed due to inactivity and irreproducibility
