### ISSUE TITLE
Extra info regarding the tilt animation for the documentation

### ISSUE THREAD

**Issue by brunophilipe** [antiguab/BAFluidView#49]
I was having problems with the tilt animation, and I couldn't get it to work. I would trace all the function calls all the way to the library adding the 3D animation to the layer, and yet it did not work.

But then I noticed that the only difference between my code and the example is that I called 

```
fluidView.startAnimation()
fluidView.startTiltAnimation()
```

inside of `viewDidLoad()`. Moving those calls to `viewDidAppear` fixed the problem. I think you could perhaps want to add this to the Read-me file.

Awesome job with the view! 👍

**Comment by antiguab** [comment]
awesome! sorry for the late response but I'll do that!
