### ISSUE TITLE
Tilt won't work if device starts app while laying flat on surface

### ISSUE THREAD

**Issue by matcartmill-old** [antiguab/BAFluidView#52]
If I start the app while holding my phone in my hand in an upright position, the tilting functionality works well. However, if app is launched while the device is flat on a desk or counter top, the tilting functionality will not work once the device is picked up.

**Comment by antiguab** [comment]
if this is still an issue - let me know, and I'll investigate!

**Comment by Muirey03** [comment]
@antiguab this will be fixed if you accept [this pull request](https://github.com/antiguab/BAFluidView/pull/64).
