### ISSUE TITLE
How to fill the view and keep the filler stationary ?

### ISSUE THREAD

**Issue by sriteja25** [antiguab/BAFluidView#55]
Thanks a lot for the pod, it looks great.

I am try to use this in one of my project where i want to use this as a progress view where the fluid fills out my view. I have tried 

myView.fillAutoReverse = false and it doesnot work.

Can anyone please help me how to keep the filler stationary after it has made till 80% of the view ?

**Comment by antiguab** [comment]
have you tried calling `keepStationary` after the animation has completed? If so, can you send me a code snippet of what you're doing? thanks!
