### ISSUE TITLE
Swift Implementation

### ISSUE THREAD

**Issue by gemamegantara** [antiguab/BAFluidView#56]
Hi, I'm trying to implement this great lib on swift, by writing this code:

        let fluidView = BAFluidView(frame: self.view.frame, startElevation: 0.9)!
        
        fluidView.strokeColor = UIColor.green
        fluidView.fillColor = Constants.COLOR_BLUE
        fluidView.keepStationary()
        fluidView.startAnimation()
        
        self.view.addSubview(fluidView)

and here is the preview:
![screen shot 2017-04-06 at 6 53 53 pm](https://cloud.githubusercontent.com/assets/1680992/24752971/733386ac-1afa-11e7-9860-b21c6ff9946f.png)

I've been changing the value of startElevation from 0.1 to 9000, but the height of wave didn't change. I want to achieve that the height of wave is 1/4 of the height screen.

Thank you.

**Comment by ImmanuelKannan** [comment]
Hey I'm not sure if this will help you, but are you by chance writing your code in viewDidLoad? If so, try writing it in viewDidAppear. I was having the same problem, implemented it in viewDidAppear and now its working as expected.

**Comment by antiguab** [comment]
Apologies for the late response! I agree with @ImmanuelKannan, have you checked where you initialize? It could be the case that your final frame isn't set yet if you're in `viewDidLoad`.
