### ISSUE TITLE
Use accelerometer to influence fluid

### ISSUE THREAD

**Issue by martinjo** [antiguab/BAFluidView#8]
It would be cool if the accelerometer was used to influence how to fluid behaves. I guess that would require some sort of physics simulation, but it would still be cool :)

**Comment by antiguab** [comment]
I've actually been thinking about that! It's what I want to tackle in the next version.

**Comment by VictorSharov** [comment]
I will wait it too!

**Comment by antiguab** [comment]
Feature added! Check out version 2.0!
